### ISSUE TITLE
$algoliaSettings['attributesForFaceting'] setting is being ignored.

### ISSUE THREAD

**Issue by mspivak** [algolia/algoliasearch-laravel#51] opened 2016-02-03 21:56 UTC
Hi there,

Each time I run `Product::reindex();` the `attributesForFaceting` setting gets cleared on my dashboard and I must login and update it manually. Am I doing it wrong?

```
class Product extends \ResourceModel {
	use AlgoliaEloquentTrait;
	public static $perEnvironment = true;
	public static $autoIndex = true;
	public $algoliaSettings = [
		'attributesForFaceting' => [ 'category_id', 'vendor_id', 'unit_price', 'brand' ],
	];
}
```

Thanks in advance!

**Comment by Nikita240** [comment] 2016-02-04 00:43
+1 same issue

**Comment by Nikita240** [comment] 2016-02-04 01:21
Turns out this is intended behaviour.

See the part in blue:

![image](https://cloud.githubusercontent.com/assets/6479817/12802842/91ace756-ca9a-11e5-8aa1-f74f13461367.png)

**Comment by maxiloc** [comment] 2016-02-04 07:51
Yes you need to do setSettings after the full reindex. Let keep this open as we might want to handle it in the reindex method

**Comment by mspivak** [comment] 2016-02-06 00:04
You're right @maxiloc. Doing `setSettings` after `reindex` fixes the thing. I would suggest adding it by default, since one wouldn't expect that reindexing resets the index settings!

**Comment by JanPetr** [comment] 2016-05-23 13:24
Fixed by #64. Feature will be part of next release.

**Closed** 2016-05-23 13:23 UTC

**Comment by GiampaoloFalqui** [comment] 2016-09-26 15:44
This issue presents itself also on [algoliasearch-laravel4](https://github.com/algolia/algoliasearch-laravel-4) branch - tested now.
