### ISSUE TITLE
Algolia Exception: No content in PUT request

### ISSUE THREAD

**Issue by FredrikOseberg** [algolia/algoliasearch-laravel#63] opened 2016-05-21 01:54 UTC
Hi, I'm having trouble getting Algolia to index my model. After following the instructions to set it up (require it in with composer, add class to providers array, publish vendor and update config API keys, and adding trait to model class) I am getting the following error when making a POST request on a form submission: 

AlgoliaException in Client.php line 910:
No content in PUT request
in Client.php line 910
at Client->doRequest(object(ClientContext), 'PUT', 'K0QKLYIYQ7.algolia.net', '/1/indexes/activities/4', array(), array('category_id' => '1', 'activityTitleNor' => 'Dette er an test', 'activityDescriptionNor' => 'Test ', 'price' => '200', 'supplier_id' => '1', 'safetyNor' => 'Supersafe', 'updated_at' => '2016-05-21 01:53:46', 'created_at' => '2016-05-21 01:53:46', 'id' => '4', 'objectID' => '4'), '2', '30') in Client.php line 738

Now after looking around for two days on google trying to locate any information about this issue I've failed to resolve it on my own, this leads me to believe that it's either A) so obvious to experienced developers that no one thought to put the information anywhere or B) a new issue.

I'm running laravel 5.2 on Homestead.

**Comment by JanPetr** [comment] 2016-05-23 11:16
Hey @Kharebear, it's weird I'm not able to reproduce your issue. I tried to perform the same request as you pasted here and it works correctly and adds/updates record in the index.

Can you try to run the request independently on Laravel extension? Just try to run:
```php
$client->doRequest(<put ClientContext object here>, 
'PUT', 
'K0QKLYIYQ7.algolia.net', 
'/1/indexes/activities/4', 
array(), 
array('category_id' => '1', 'activityTitleNor' => 'Dette er an test', 'activityDescriptionNor' => 'Test ', 'price' => '200', 'supplier_id' => '1', 'safetyNor' => 'Supersafe', 'updated_at' => '2016-05-21 01:53:46', 'created_at' => '2016-05-21 01:53:46', 'id' => '4', 'objectID' => '4'), 
'2', 
'30');
```
to see if it fails with same error and we can localize the error. If it's the issue with Laravel extension or our PHP client itself.

Thanks!

**Comment by maxiloc** [comment] 2016-09-07 09:07
I am closing this, feel free to re-open if needed

**Closed by maxiloc** 2016-09-07 09:07 UTC
