### ISSUE TITLE
_geoloc object can't be submitted via update method

### ISSUE THREAD

**Issue by stoicbuddha** [algolia/algoliasearch-laravel#56] opened 2016-04-13 22:30 UTC
When you attempt to update via the update() method, you can't send _geoloc.  You can set it as an array, an object, whatever; it won't work.  You get an error saying that _geoloc can't contain a string, and if you look at the body of the request in the logs, you can see it's sending _geoloc as blank.

**Comment by rayrutjes** [comment] 2016-05-20 09:43
Hi @stoicbuddha, sorry for the late reply. Could you give us the piece of code you are using so we can try it ou?

**Comment by stoicbuddha** [comment] 2016-05-20 10:14
```
		$update = array(
			'name' => $_POST['name'],
			'website' => $_POST['website'],
			'description' => $_POST['description'],
			...
			'_geoloc' => array( 'lat' => $lat, 'long' => $long),
                                   
			);
			
		$alg_update = $business->find($id);
		
		$alg_update->update($update);
```

I also tried passing the array in _geoloc as an object, tried typecasting the values as floats/ints/etc, to no avail.  I've noticed pretty much everything gets typecast to a string unless you explicitly typecast it as whatever type of number it should be.

**Comment by JanPetr** [comment] 2016-05-20 12:50
Hey @stoicbuddha,
I can see the problem. We accept only `lat` and `lng` attributes in `_geoloc`. And you have a typo as you are trying to send `long` instead of `lng`.

Can you confirm if it sorted out your problem? Otherwise, could you send me the version of the plugin you are using? Thanks!

**Comment by stoicbuddha** [comment] 2016-05-20 14:49
No, that was actually a typo when I was typing out that section of code.  I had to create a workaround by editing the core Algolia files in my project, so I tried pulling it from memory.

**Comment by JanPetr** [comment] 2016-05-23 12:02
Hello @stoicbuddha,
ok. But unfotunatelly I'm not able to reproduce the issue. I just tried to update `_geoloc` in my models and everything works correctly and location is updated in DB and in Algolia index as well.
Can you tell me what change did you ve to make to make it work on your side? Concerete files and lines will be the best!

And do you store `_geoloc` in the same model or do you have there some relation with another model?

Thanks for your help!

**Comment by stoicbuddha** [comment] 2016-05-23 12:57
Client.php around the 780 mark.  I have it doing a search for before the data is formatted for the request to set things properly.  I now send lat/long as their own sets of data, and set up the array on the tail end before the jSON bit.

As a side note, I'd also like to mention that mandatory typecasting for PHP should be noted in your docs.  I got to find out the hard way that everything had to be typecast or else it'd pull it as a string.

**Comment by stoicbuddha** [comment] 2016-05-23 13:04
Can you show me exactly how you have your request set up for the `_geoloc` object?

**Comment by JanPetr** [comment] 2016-05-23 13:41
I do it the same way as you according yours messages above.

Model:
```php
class Task extends Model
{
    use AlgoliaEloquentTrait;

    protected $fillable = ['title', '_geoloc'];

    protected $casts = [
        '_geoloc' => 'array',
    ];
}
```

Updating:
```php
$task = Task::find(5);
$task->update([
    'title' => 'Foo',
    '_geoloc' => ['lat' => 12, 'lng' => 16]
]);
```

Formatted data in `doRequest` method in Client.php:
```php
array (size=6)
  'id' => int 5
  'title' => string 'Foo' (length=3)
  'created_at' => string '2016-05-23 10:55:57' (length=19)
  'updated_at' => string '2016-05-23 13:37:51' (length=19)
  '_geoloc' => 
    array (size=2)
      'lat' => int 12
      'lng' => int 16
  'objectID' => int 5
```

Everything is indexed as expected.

Do you have any difference there?

**Comment by maxiloc** [comment] 2016-09-07 09:10
I am closing this, feel free to re-open if needed ?

**Closed by maxiloc** 2016-09-07 09:10 UTC

**Comment by be-mohand** [comment] 2017-11-20 21:50
I am having the same issue, even if I am not using Laravel but CakePHP.

Maybe is it an issue with PHP v7.1?
