### ISSUE TITLE
Hosts unreachable

### ISSUE THREAD

**Issue by RyanHavoc** [algolia/algoliasearch-laravel#59] opened 2016-05-12 12:03 UTC
I've done a fresh install of Homestead, VirtualBox, freshly downloaded the Vagrant box and am using the latest version algoliasearch-laravel however for some reason I'm getting this error:

```
AlgoliaException in Client.php line 748:
Hosts unreachable: Could not resolve host: WWPOIMBJ3Z .algolia.net,Could not resolve host: WWPOIMBJ3Z -3.algolianet.com,Could not resolve host: WWPOIMBJ3Z -1.algolianet.com,Could not resolve host: WWPOIMBJ3Z -2.algolianet.com
```

We've been using Algolia for 6 months and this is the first time I've had this issue and I'm stumped as to how to resolve it?

**Comment by aseure** [comment] 2016-05-12 12:14
Hello @RyanHavoc. Just to keep track of what we said this morning, we added those lines to the `Vagrantfile` to make VirtualBox use the host DNS to resolve queries but it didn't work:

```
config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
end
```

**Comment by asurak** [comment] 2016-05-12 12:26
We have seen this issue before with Vagrant. If inside the Vagrant box you'll try to run:
`time curl http://WWPOIMBJ3Z .algolia.net` you'll see a really big time. The same thing should happen when you do `time host WWPOIMBJ3Z .algolia.net`. The issue is not on the side of our API but inside the Vagrant box. The reason you see the API client error is that we enforce timeout that is lower than how quickly the box can resolve the domain.

**Comment by RyanHavoc** [comment] 2016-05-12 12:33
@aseure Correct, adding that to my Vagrantfile didn't make a difference. Thought it would be helpful to raise this issue here also seen as this package relates specfically to Laravel. My Homestead Vagrantfile now looks like this:

```
require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION = "2"
confDir = $confDir ||= File.expand_path("~/.homestead")

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exists? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exists? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    end

    Homestead.configure(config, settings)

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
end
```

As I say, doesn't seem to make a difference.

@asurak When I run those commands I don't get a big number I get a host not found errors:

<img width="453" alt="1 vagrant homestead vagrant" src="https://cloud.githubusercontent.com/assets/824169/15214597/d312854a-1845-11e6-8325-29c0240131f8.png">

The error I get in full is:

```
AlgoliaException in Client.php line 748:
Hosts unreachable: Could not resolve host: WWPOIMBJ3Z .algolia.net,Could not resolve host: WWPOIMBJ3Z -3.algolianet.com,Could not resolve host: WWPOIMBJ3Z -2.algolianet.com,Could not resolve host: WWPOIMBJ3Z -1.algolianet.com
in Client.php line 748
at Client->request(object(ClientContext), 'POST', '/1/indexes/users', array(), array('firstname' => 'Ryan', 'lastname' => 'Taylor', 'username' => 'RyanHavoc', 'updated_at' => '2016-05-12 12:27:13', 'created_at' => '2016-05-12 12:27:13', 'id' => '4', 'meta' => array('follower_count' => '0', 'following_count' => '0', 'auth_user_follows' => false, 'auth_user_blocks' => false, 'is_photographer' => false, 'is_editor' => false, 'is_admin' => false, 'has_payout_details' => false, 'payout_service' => false, 'photographer_cover' => null), 'photographer' => null, 'profile' => null, 'editor' => null, 'billing' => null, 'images' => null, 'timestamps' => array('born_at' => null), 'objectID' => '4'), array('WWPOIMBJ3Z .algolia.net', 'WWPOIMBJ3Z -3.algolianet.com', 'WWPOIMBJ3Z -2.algolianet.com', 'WWPOIMBJ3Z -1.algolianet.com'), '4', '40') in Index.php line 141
at Index->addObject(array('firstname' => 'Ryan', 'lastname' => 'Taylor', 'username' => 'RyanHavoc', 'updated_at' => '2016-05-12 12:27:13', 'created_at' => '2016-05-12 12:27:13', 'id' => '4', 'meta' => array('follower_count' => '0', 'following_count' => '0', 'auth_user_follows' => false, 'auth_user_blocks' => false, 'is_photographer' => false, 'is_editor' => false, 'is_admin' => false, 'has_payout_details' => false, 'payout_service' => false, 'photographer_cover' => null), 'photographer' => null, 'profile' => null, 'editor' => null, 'billing' => null, 'images' => null, 'timestamps' => array('born_at' => null), 'objectID' => '4')) in AlgoliaEloquentTrait.php line 251
at User->pushToIndex() in User.php line 149
at User::PMH\{closure}(object(User))
at call_user_func_array(object(Closure), array(object(User))) in Dispatcher.php line 221
at Dispatcher->fire('eloquent.saved: PMH\User', array(object(User))) in Model.php line 1679
at Model->fireModelEvent('eloquent.saved: PMH\User', false) in Model.php line 1514
at Model->finishSave(array()) in Model.php line 1485
at Model->save() in Model.php line 571
at Model::create(array('_token' => 'Q2CwhxnPozl7ovKYTqEkxRK8LemQoTWFgEH4mlnb', 'fakeusernameremembered' => '', 'fakepasswordremembered' => '', 'firstname' => 'Ryan', 'lastname' => 'Taylor', 'email' => 'ryan@nodividestudio.com', 'username' => 'RyanHavoc', 'password' => 'secret', 'email_confirmation_code' => '87624f98d5d728779fae71e6716bd18c')) in EloquentUserRepository.php line 60
at EloquentUserRepository->create(array('_token' => 'Q2CwhxnPozl7ovKYTqEkxRK8LemQoTWFgEH4mlnb', 'fakeusernameremembered' => '', 'fakepasswordremembered' => '', 'firstname' => 'Ryan', 'lastname' => 'Taylor', 'email' => 'ryan@nodividestudio.com', 'username' => 'RyanHavoc', 'password' => secret', 'email_confirmation_code' => '87624f98d5d728779fae71e6716bd18c')) in AuthController.php line 64
at AuthController->create(array('_token' => 'Q2CwhxnPozl7ovKYTqEkxRK8LemQoTWFgEH4mlnb', 'fakeusernameremembered' => '', 'fakepasswordremembered' => '', 'firstname' => 'Ryan', 'lastname' => 'Taylor', 'email' => 'ryan@nodividestudio.com', 'username' => 'RyanHavoc', 'password' => 'secret')) in AuthController.php line 155
at AuthController->postRegister(object(Request))
at call_user_func_array(array(object(AuthController), 'postRegister'), array(object(Request))) in Controller.php line 80
at Controller->callAction('postRegister', array(object(Request))) in ControllerDispatcher.php line 146
at ControllerDispatcher->call(object(AuthController), object(Route), 'postRegister') in ControllerDispatcher.php line 94
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in RedirectIfAuthenticated.php line 42
at RedirectIfAuthenticated->handle(object(Request), object(Closure))
at call_user_func_array(array(object(RedirectIfAuthenticated), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'postRegister') in ControllerDispatcher.php line 54
at ControllerDispatcher->dispatch(object(Route), object(Request), 'PMH\Http\Controllers\Auth\AuthController', 'postRegister') in Route.php line 174
at Route->runController(object(Request)) in Route.php line 140
at Route->run(object(Request)) in Router.php line 724
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in VerifyCsrfToken.php line 64
at VerifyCsrfToken->handle(object(Request), object(Closure)) in VerifyCsrfToken.php line 26
at VerifyCsrfToken->handle(object(Request), object(Closure))
at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 62
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))
at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 726
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
at Router->dispatchToRoute(object(Request)) in Router.php line 675
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
at Debugbar->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 51
```

**Comment by asurak** [comment] 2016-05-12 12:34
@RyanHavoc you have space after you APPID

**Comment by asurak** [comment] 2016-05-12 12:37
@RyanHavoc and for the host test, it has to be `time host WWPOIMBJ3Z .algolia.net` - without the `http://`

**Comment by RyanHavoc** [comment] 2016-05-12 12:39
@asurak Apologies. I copy and pasted from you comment and for some reason it added a space. :-(

Now I get this:

<img width="453" alt="1 vagrant homestead ssh" src="https://cloud.githubusercontent.com/assets/824169/15214771/e6bdc43c-1846-11e6-905f-a524cc4e9354.png">

**Comment by asurak** [comment] 2016-05-12 12:44
The first one is a correct output, the second one is not. Can you run `dig WWPOIMBJ3Z .algolia.net` ?

**Comment by RyanHavoc** [comment] 2016-05-12 12:57
OK, that gives me:

<img width="498" alt="1 vagrant homestead ssh" src="https://cloud.githubusercontent.com/assets/824169/15215239/5b36872a-1849-11e6-9848-af9da35260b6.png">

**Comment by asurak** [comment] 2016-05-12 13:00
That looks ok but it does not match the error the PHP produces. Do you have `hhvm.server.dns_cache.enable` set to `true` in HHVM?

**Comment by RyanHavoc** [comment] 2016-05-12 13:03
Don't appear to have. This is what's set it /etc/hhvm/server.ini:

<img width="498" alt="1 vagrant homestead etc hhvm ssh" src="https://cloud.githubusercontent.com/assets/824169/15215393/392b47aa-184a-11e6-8c73-e9cad7771d2d.png">

And this is what's set in /etc/hhvm/php.ini:

<img width="498" alt="1 vagrant homestead etc hhvm ssh" src="https://cloud.githubusercontent.com/assets/824169/15215401/4cb33a4e-184a-11e6-8f79-a85d877b1948.png">

**Comment by RyanHavoc** [comment] 2016-05-12 13:50
@asurak If this was a DNS resolution issue as @aseure suggests wouldn't I be having problems curling anything? I get the proper response when I curl my website for example...

**Comment by asurak** [comment] 2016-05-12 15:08
The DNS resolutions issues we have seen with Vagrant did not stop the system from working but the resolution was very slow. Our PHP API client has timeout of 2 seconds for the initial connection and if the resolution is not fast enough, the client gives up.

**Comment by RyanHavoc** [comment] 2016-05-12 17:19
@asurak We're not seeing evidence of that in this case though, host and curl are responding quickly. Any idea on what else I could try? I'm really stuck here as I it's preventing me from working on our platform locally...

**Comment by asurak** [comment] 2016-05-12 17:55
Honestly Ryan, I have no idea what could be wrong. The issue is definitely in the way PHP interacts with the system, the client and the API are ok. Can I get a copy of your Vagrant box? Last time I was troubleshooting issue like this I ended-up with strace :)

**Comment by RyanHavoc** [comment] 2016-05-12 18:55
@asurak I appreciate your help. I'm literally running a fresh install of Homestead so if you follow the instructions here you'll have what I have: https://laravel.com/docs/5.2/homestead

**Comment by RyanHavoc** [comment] 2016-05-12 18:56
I'm using VirtualBox 5.

**Comment by asurak** [comment] 2016-05-13 07:22
thanks, I'll dive into that...there is no way we leave this unresolved

**Comment by RyanHavoc** [comment] 2016-05-13 09:00
@asurak I really appreciate it. I'm truly at a loss with this. We've been using Algolia for 6 months on this platform and love it and this is the first time we've had any issues of this kind. If I can provide any more information that would be useful please let me know.

**Comment by asurak** [comment] 2016-05-13 09:48
@RyanHavoc I'm working on that... so far I see that the DNS server 10.0.2.3 is modifying the answers.
Response of 10.0.2.3:
```
;; ANSWER SECTION:
latency-dsn.algolia.net. 3600	IN	CNAME	c1-eu-1.algolia.net.
c1-eu-1.algolia.net.	3600	IN	A	5.196.77.97
```

Response of 8.8.8.8:
```
;; ANSWER SECTION:
latency-dsn.algolia.net. 59	IN	CNAME	dsn.latency.algolia.net.
dsn.latency.algolia.net. 59	IN	CNAME	c1-eu-2.algolia.net.
c1-eu-2.algolia.net.	3599	IN	A	149.202.74.46
```

That they resolve to a different IPs is not a problem, there is round-robin in the DNS.

This is more worrying:
```
vagrant@homestead:~$ host latency-dsn.algolia.net 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

latency-dsn.algolia.net is an alias for dsn.latency.algolia.net.
dsn.latency.algolia.net is an alias for c1-eu-3.algolia.net.
c1-eu-3.algolia.net has address 37.187.25.29
vagrant@homestead:~$ host latency-dsn.algolia.net 10.0.2.3
Using domain server:
Name: 10.0.2.3
Address: 10.0.2.3#53
Aliases: 

latency-dsn.algolia.net is an alias for c1-eu-2.algolia.net.
c1-eu-2.algolia.net has address 149.202.74.46
Host c1-eu-2.algolia.net not found: 4(NOTIMP)
Host c1-eu-2.algolia.net not found: 4(NOTIMP)
```

**Comment by RyanHavoc** [comment] 2016-05-13 10:47
@asurak I'll be honest. I'm not sure what I'm looking at here. DNS isn't my forte... but if you're worried I'm worried.

Are these results from your own Homestead instance?

**Comment by asurak** [comment] 2016-05-13 11:24
I can reproduce the issue very reliably. Vanilla ubuntu/trusty64 box is not doing it but I have a way how to force it to have the same issue. Right now I'm investigating where in the Homestead box are these settings enforced

**Comment by asurak** [comment] 2016-05-13 11:42
@RyanHavoc need your verification ;)

1. Please remove the modification from your `Vagrantfile` so you have the clean repo
2. In the Homestead repo where you create the Vagrant box, file `./scripts/homestead.rb`, line 36, change `vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]` to `vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]`
3. `vagrant reload`

**Comment by RyanHavoc** [comment] 2016-05-13 12:29
@asurak I got excited then but no joy unfortunately.

I set my Vagrantfile back to how it was and change the natdnshostresolver1 on line 36 to off. Reload didn't make a difference so I destroyed the box and build it up again but I'm still getting the same error...

**Comment by asurak** [comment] 2016-05-13 12:37
This is my `git diff` from the clean laravel/homestead repository:
```
diff --git a/scripts/homestead.rb b/scripts/homestead.rb
index ab29d83..8c53db3 100644
--- a/scripts/homestead.rb
+++ b/scripts/homestead.rb
@@ -33,7 +33,7 @@ class Homestead
       vb.customize ["modifyvm", :id, "--memory", settings["memory"] ||= "2048"]
       vb.customize ["modifyvm", :id, "--cpus", settings["cpus"] ||= "1"]
       vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
-      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
+      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
       vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
     end
```

Do you have any other changes?

**Comment by RyanHavoc** [comment] 2016-05-13 12:48
No, mines exactly the same:

```
RyanT:~/Homestead (master)$ git diff
diff --git a/scripts/homestead.rb b/scripts/homestead.rb
index ab29d83..8c53db3 100644
--- a/scripts/homestead.rb
+++ b/scripts/homestead.rb
@@ -33,7 +33,7 @@ class Homestead
       vb.customize ["modifyvm", :id, "--memory", settings["memory"] ||= "2048"]
       vb.customize ["modifyvm", :id, "--cpus", settings["cpus"] ||= "1"]
       vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
-      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
+      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
       vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
     end
```

**Comment by asurak** [comment] 2016-05-15 09:57
Does the `host` command still return the same `NOTIMP` error?

**Comment by RyanHavoc** [comment] 2016-05-15 10:41
@asurak Yes it does:

<img width="498" alt="1 vagrant homestead bash" src="https://cloud.githubusercontent.com/assets/824169/15273377/afdf1a7e-1a8f-11e6-98b0-e4dc9b953550.png">

BUT! I spent most yesterday diagnosing and testing. I started off installing a new instance of Laravel along with algoliasearch-laravel package and created a simple model to sync. That worked first time with my existing config of Vagrant/Homestead/Virtualbox. So that suggested to me that it wasn't a Homestead issue... So I wanted to then test on a different machine so I got everything installed on one of my Project Managers laptops and pulled down the master branch of our repo that I'm having the problems with. This worked fine as well...

At this point I was stumped. The build on my machine was exactly the same as the one I had on the laptop but mine threw the Hosts unreachable error without fail. I composer updated, all packages were up to date, I checked the Git logs and they matched each other. I knew that it wasn't a Homestead issue because I'd done that simple test build and that worked. So I completely deleted my local build, git repo, database, the lot, I then blanked Homestead again and reinstalled absolutely everyone from scratch. Low and behold when I pulled everything down again it worked first time!

I honestly can't explain it. I compared everything I could think of and they were identical on each machine. It was such a specific issue as well that it's just odd. I'm annoyed but also relieved to be back up and running.

BTW this is with the `natdnshostresolver1` set to `on` as well.

I think we can close this issue, it's just annoying that we didn't get to the bottom of the cause. :-(

I really appreciate your help! Thank you.

**Comment by asurak** [comment] 2016-05-16 06:57
@RyanHavoc just out of curiosity, can you also change `vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]` to `vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]` ? Which version of VirtualBox are you using? I've 5.0.20

**Comment by RyanHavoc** [comment] 2016-05-16 15:52
@asurak So I got thing working on Saturday but today I've just had that AlgoliaException relating to the timeout issue in milliseconds. This is new, I'd not had that before. I've change the natdnsresolver1 to off in homestead.rb and that has fixed it. Very bizarre.

**Comment by maxiloc** [comment] 2016-09-07 09:08
I am closing this, feel free to re-open if needed

**Closed by maxiloc** 2016-09-07 09:08 UTC
